---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.7"

inputs:
- name: broker-src
  path: gopath/src/github.com/cloudfoundry-community/cf-uaa-guard-proxy
- name: broker-config

run:
  path: broker-config/tasks/test-proxy.sh
